namespace Agnosia.Android.Commands;

internal enum AndroidCommandKind
{
    ProfilePing,
    QueryApps,
    QueryAppIcon,
    QueryAppIcons,
    QueryLogs,
    QueryCrossProfilePackages,
    QueryPermissions,
    QueryUsageStatsAccess,
    QueryPackageInstallAccess,
    QueryAllFilesAccess,
    QueryPackageState,
    RequestUsageStatsAccess,
    RequestPackageInstallAccess,
    RequestAllFilesAccess,
    InstallPackage,
    UninstallPackage,
    FreezePackage,
    UnfreezePackage,
    RevokeRuntimePermissions,
    SetLockdownEnabled,
    SetLockdownInternetAccess,
    PrepareHiddenShortcut,
    CreateHiddenShortcut,
    UnfreezeAndLaunch,
    LaunchAppProxy,
    SetCrossProfileInteraction,
    StartFileShuttleParentToWork,
    StartFileShuttleWorkToParent,
    SynchronizePreference,
    FinalizeProvision,
    PackageInstallerCallback
}
