namespace Agnosia.Android.Permissions;

public sealed record AppPermissionRiskInput(
    IEnumerable<string>? RequestedPermissions,
    int DeviceSdkVersion = 31,
    int TargetSdkVersion = 0,
    IEnumerable<string>? ForegroundServiceTypes = null,
    IEnumerable<string>? ServicePermissions = null,
    IEnumerable<string>? GrantedPermissions = null,
    IEnumerable<string>? DeniedPermissions = null,
    bool? IsAccessibilityServiceEnabled = null,
    bool? IsNotificationListenerEnabled = null,
    bool? CanDrawOverlays = null,
    bool? HasUsageStatsAccess = null,
    bool? IsCameraAppOpAllowed = null,
    bool? IsMicrophoneAppOpAllowed = null,
    bool? IsFineLocationAppOpAllowed = null,
    bool? IsCoarseLocationAppOpAllowed = null,
    IEnumerable<string>? ObservedSignals = null,
    bool? IsVpnControlEnabled = null,
    bool? IsAssistantScreenContentEnabled = null,
    bool? IsMediaProjectionActive = null,
    bool? HasManageExternalStorageAccess = null,
    bool? CanRequestPackageInstalls = null,
    bool? CanScheduleExactAlarms = null,
    bool? IsIgnoringBatteryOptimizations = null,
    bool? IsLocalNetworkRestrictionEnabled = null,
    IEnumerable<string>? ForegroundOnlyPermissions = null,
    IEnumerable<string>? UnavailableAppOpPermissions = null,
    bool? IsInputMethodEnabled = null,
    bool? IsAutofillServiceEnabled = null,
    bool? IsDeviceAdminEnabled = null,
    IEnumerable<string>? BlockedAppOpPermissions = null,
    bool? HasLegacyExternalStorageAccess = null);
